arm_left:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001
arm_right:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001
both_arms:
  #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  #kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.1 # Shorter timeout is often possible with Trac-IK
  kinematics_solver_attempts: 10
  #kinematics_solver_search_resolution: 0.0050000000000000001
  #kinematics_solver_timeout: 0.0050000000000000001